const TYPES = {
   INPUT: 'INPUT',
   ADD: 'ADD',
   CHECK: 'CHECK',
   CHECK_ALL: 'CHECK_ALL',
   EDIT: 'EDIT',
   EDIT_INPUT: 'EDIT_INPUT',
   EDIT_STATUS: 'EDIT_STATUS',
   REMOVE: 'REMOVE',
   CHANGE_FILTER: 'CHANGE_FILTER',
   CLEAR: 'CLEAR',
   CONFIRM: 'CONFIRM',
   HIDE_CONFIRM: 'HIDE_CONFIRM'
}

export default TYPES
